services:
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ./docker/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nest:
    build:
      context: . # src 폴더에 Dockerfile을 두고 빌드
    container_name: nest-app
    ports:
      - '3000:3000' # NestJS가 3000번 포트에서 실행됨
    environment:
      NODE_ENV: production
    networks:
      - app-network
    depends_on:
      - db

  nginx:
    image: nginx:latest
    container_name: nginx-server
    ports:
      - '80:80' # Nginx가 80번 포트에서 수신
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginx 설정 파일
    depends_on:
      - nest
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
